// Generated by CoffeeScript 1.6.2
(function() {
  var PriorityQueue;

  PriorityQueue = (function() {
    function PriorityQueue() {}

    PriorityQueue.constructor = function() {
      return this.items = [null];
    };

    return PriorityQueue;

  })();

  exports.PriorityQueue = PriorityQueue;

}).call(this);
